# Generated by Django 6.1.1 on 2026-09-09 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MocAffectedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=30)),
                ('object_id', models.UUIDField()),
                ('impact_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_objects', to='engineering.mocrequest')),
            ],
            options={
                'db_table': 'moc_affected_objects',
            },
        ),
        migrations.CreateModel(
            name='EngineeringCalculationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.IntegerField()),
                ('inputs', models.JSONField()),
                ('assumptions', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('change_reason', models.TextField(blank=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='engineering.engineeringcalculation')),
            ],
            options={
                'db_table': 'engineering_calculation_revisions',
                'constraints': [models.UniqueConstraint(fields=('calculation', 'revision_number'), name='engineering_calc_revision_number')],
            },
        ),
        migrations.CreateModel(
            name='MocReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(max_length=50)),
                ('reviewer_id', models.UUIDField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='engineering.mocrequest')),
            ],
            options={
                'db_table': 'moc_reviews',
                'constraints': [models.UniqueConstraint(fields=('moc', 'review_type'), name='moc_review_type')],
            },
        ),
    ]
