# Generated by Django 6.1.1 on 2026-09-09 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_mocaffectedobject_engineeringcalculationrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringauditlog',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='engineeringauditlog',
            name='event_type',
            field=models.CharField(default='engineering.changed', max_length=100),
        ),
        migrations.AddField(
            model_name='engineeringauditlog',
            name='revision',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
