# Generated by Django 6.1.1 on 2026-09-05 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='attachments',
        ),
        migrations.RenameModel(
            old_name='ChatSession',
            new_name='chat_sessions',
        ),
        migrations.RenameModel(
            old_name='Chat',
            new_name='chats',
        ),
    ]
